### ISSUE TITLE
windows能用了吗？

### ISSUE THREAD

**Issue by disburden** [Kingtous/Fclash#10]
rt

我看没有release widnows版的，是不是要自己下载源码到widnows下编译？还是目前还不支持windows？

**Comment by Kingtous** [comment]
目前不支持windows，会在下次重构增加windows、macos支持

**Comment by Kingtous** [comment]
现已支持Windows版本，刚出，可以测试一下。

**Comment by Kingtous** [comment]
先close了，有问题请开新issue反馈哈
