### ISSUE TITLE
如何设置为每次启动自动启动系统代理模式？

### ISSUE THREAD

**Issue by shenmo7192** [Kingtous/Fclash#16]
在之前的版本中默认开启，但是现在似乎不会了，需要手动点一下才行
如何破？

**Comment by Kingtous** [comment]
只要第一次手动点一下就行吧，后面是会记忆的，之前的版本也是这样的。

**Comment by shenmo7192** [comment]
![录屏_选择区域_20220918004424](https://user-images.githubusercontent.com/47873776/190867532-b2ce597a-e692-43eb-a3bf-06ad8af12477.gif)

**Comment by Kingtous** [comment]
> ![录屏_选择区域_20220918004424](https://user-images.githubusercontent.com/47873776/190867532-b2ce597a-e692-43eb-a3bf-06ad8af12477.gif) [ ![录屏_选择区域_20220918004424](https://user-images.githubusercontent.com/47873776/190867532-b2ce597a-e692-43eb-a3bf-06ad8af12477.gif) ](https://user-images.githubusercontent.com/47873776/190867532-b2ce597a-e692-43eb-a3bf-06ad8af12477.gif) [ ](https://user-images.githubusercontent.com/47873776/190867532-b2ce597a-e692-43eb-a3bf-06ad8af12477.gif)

会不会只是tray没有刷新？打开后虽然显示不是系统代理，但是确实已经是系统代理？

**Comment by Kingtous** [comment]
修正了下，目前点击退出，会连着fclash的自动配置代理一起清除。发个新版~

**Comment by shenmo7192** [comment]
> 修正了下，目前点击退出，会连着fclash的自动配置代理一起清除。发个新版~

收到

**Comment by Kingtous** [comment]
> > 修正了下，目前点击退出，会连着fclash的自动配置代理一起清除。发个新版~
> 
> 收到

已申请更新至spark store :)
