### ISSUE TITLE
Ask

### ISSUE THREAD

**Issue by Juminiy** [Kingtous/Fclash#2]

**Comment by Juminiy** [comment]
How to install the application in ios (iPhone & iPad) ?

**Comment by Kingtous** [comment]
its not supported in iOS, u can consider shadowrocket.

**Comment by Juminiy** [comment]
thanks!

**Comment by Juminiy** [comment]
can build on windows platform ?

**Comment by Kingtous** [comment]
> 

short answer is yes. It requires short changes in the source code. I'll make a new branch called 'windows' and test fclash on windows platform.
