### ISSUE TITLE
开启启动时隐藏后如何恢复？

### ISSUE THREAD

**Issue by TailendWong** [Kingtous/Fclash#21]
在mac os 12.x中，安装了fclash.dmg。当我将Setting中的启动时隐藏开启后，想要在恢复该选项，但我已经打不开那个界面了。请问该如何操作才能恢复

**Comment by Kingtous** [comment]
之前没在mac上测试过，不好意思。

可以删掉defaults信息，注意会丢失原有订阅

终端输入：
`defaults delete com.kingtous.fclash`

**Comment by TailendWong** [comment]
> 可以删掉defaults信息，注意会重置默认选择的订阅，需要重新选择自己的配置文件。
> 
> 终端输入： `defaults delete com.kingtous.fclash`

非常感谢你的回复，这个解决方案帮助到了我。

你的邀请让我很激动，但是我是个javaer，对于dart属于仅听说过名字的程度，PR对我很有挑战！我只能尽力尝试下~

**Comment by Kingtous** [comment]
1.3.6已修复，以默认最小化代替了隐藏。

**Comment by iasukas** [comment]
我在debian11上遇到了同样的问题，开机它会弹出fclash is running，我点击desktop里面的启动图标，它会弹出fclash already run Now exit。我输入defaults delete com.kingtous.fclash没有效果，并没有缩小化。想问下有什么办法可以解决这个问题，因为我需要换下节点

**Comment by Kingtous** [comment]
> 我在debian11上遇到了同样的问题，开机它会弹出fclash is running，我点击desktop里面的启动图标，它会弹出fclash already run Now exit。我输入defaults delete com.kingtous.fclash没有效果，并没有缩小化。想问下有什么办法可以解决这个问题，因为我需要换下节点

你可以看看托盘图标有没有
