### ISSUE TITLE
error: unsupported rule type RULE-SET

### ISSUE THREAD

**Issue by TianboJi** [Kingtous/Fclash#25]
Fclash提示不是一个有效的配置文件，但这个yaml文件在其他客户端（如mac上的ClashX）是正常的。请问如何解决呢？

**Comment by Kingtous** [comment]
需要premium的内核代码，clash premium不开源

**Comment by Kingtous** [comment]
update: 想到一个思路，开源的clash不支持rule-provider的话，可以转换为rule再导入clash开源内核

**Comment by Kingtous** [comment]
试试1.3.8呢，增加了一个简单的转换逻辑。

https://github.com/Kingtous/Fclash/releases/tag/v1.3.8

**Comment by TianboJi** [comment]
> 试试1.3.8呢，增加了一个简单的转换逻辑。
> 
> https://github.com/Kingtous/Fclash/releases/tag/v1.3.8

我这就试试，感谢作者大大！

**Comment by TianboJi** [comment]
> 试试1.3.8呢，增加了一个简单的转换逻辑。
> 
> https://github.com/Kingtous/Fclash/releases/tag/v1.3.8

试了一下，已经可以正常使用，订阅连接也能自动转换，非常感谢！
