### ISSUE TITLE
trojan订阅出错、无法切换配置

### ISSUE THREAD

**Issue by fsrmlgd** [Kingtous/Fclash#3]
系统：ubuntu
1、trojan订阅链接返回到配置文件是一串乱码。我把订阅链接输入浏览器返回的也是这串乱码，猜想可能是需要解析
![image](https://user-images.githubusercontent.com/37462013/166688231-8964bda1-7621-4013-92bb-54396ce3ffa3.png)
2、无法切换配置文件
![image](https://user-images.githubusercontent.com/37462013/166688729-ca3916ab-3250-4ba5-86e5-d548870dc746.png)

**Comment by Kingtous** [comment]
你这个url导入其他软件例如clash for windows，可以使用吗？

**Comment by Kingtous** [comment]
> 

这边要是乐意的话，可以发送地址给我调试下，必要的话更新下程序代码。`me@kingtous.cn`，感谢反馈。

**Comment by fsrmlgd** [comment]
这个机场我很久没付费，链接类型比较多，你可以试试。
clash：https://stardream.pw/link/Ujh5Ch9K1wNhpNZF?clash=1
trojan：https://stardream.pw/link/Ujh5Ch9K1wNhpNZF?sub=4
quantumult：https://stardream.pw/link/Ujh5Ch9K1wNhpNZF?list=quantumultx
surfboard：https://stardream.pw/link/Ujh5Ch9K1wNhpNZF?surfboard=1
ssr：https://stardream.pw/link/Ujh5Ch9K1wNhpNZF?list=shadowrocket

**Comment by Kingtous** [comment]
邮箱里面这个是v2ray的订阅链接，不是clash的订阅链接哦。

使用clash的订阅链接才可以

**Comment by Kingtous** [comment]
> 这个机场我很久没付费，链接类型比较多，你可以试试。 clash：https://stardream.pw/link/Ujh5Ch9K1wNhpNZF?clash=1 trojan：https://stardream.pw/link/Ujh5Ch9K1wNhpNZF?sub=4 quantumult：https://stardream.pw/link/Ujh5Ch9K1wNhpNZF?list=quantumultx surfboard：https://stardream.pw/link/Ujh5Ch9K1wNhpNZF?surfboard=1 ssr：https://stardream.pw/link/Ujh5Ch9K1wNhpNZF?list=shadowrocket

你这里面clash的链接就可以正常导入了。

**Comment by fsrmlgd** [comment]
我知道，不过我用的是Trojan



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月5日(周四) 上午8:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Kingtous/Fclash] trojan订阅出错、无法切换配置 (Issue #3)




  
这个机场我很久没付费，链接类型比较多，你可以试试。 clash：https://stardream.pw/link/Ujh5Ch9K1wNhpNZF?clash=1 trojan：https://stardream.pw/link/Ujh5Ch9K1wNhpNZF?sub=4 quantumult：https://stardream.pw/link/Ujh5Ch9K1wNhpNZF?list=quantumultx surfboard：https://stardream.pw/link/Ujh5Ch9K1wNhpNZF?surfboard=1 ssr：https://stardream.pw/link/Ujh5Ch9K1wNhpNZF?list=shadowrocket
  
你这里面clash的链接就可以正常导入了。

**Comment by Kingtous** [comment]
> 我知道，不过我用的是Trojan
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年5月5日(周四) 上午8:53 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Kingtous/Fclash] trojan订阅出错、无法切换配置 (Issue #3) 这个机场我很久没付费，链接类型比较多，你可以试试。 clash：https://stardream.pw/link/Ujh5Ch9K1wNhpNZF?clash=1 trojan：https://stardream.pw/link/Ujh5Ch9K1wNhpNZF?sub=4 quantumult：https://stardream.pw/link/Ujh5Ch9K1wNhpNZF?list=quantumultx surfboard：https://stardream.pw/link/Ujh5Ch9K1wNhpNZF?surfboard=1 ssr：https://stardream.pw/link/Ujh5Ch9K1wNhpNZF?list=shadowrocket 你这里面clash的链接就可以正常导入了。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

clash支持trojan+v2的，只是订阅链接你需要使用clash的yaml订阅链接

**Comment by fsrmlgd** [comment]
Ok



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月5日(周四) 上午8:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Kingtous/Fclash] trojan订阅出错、无法切换配置 (Issue #3)




  
我知道，不过我用的是Trojan
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2022年5月5日(周四) 上午8:53 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [Kingtous/Fclash] trojan订阅出错、无法切换配置 (Issue #3) 这个机场我很久没付费，链接类型比较多，你可以试试。 clash：https://stardream.pw/link/Ujh5Ch9K1wNhpNZF?clash=1 trojan：https://stardream.pw/link/Ujh5Ch9K1wNhpNZF?sub=4 quantumult：https://stardream.pw/link/Ujh5Ch9K1wNhpNZF?list=quantumultx surfboard：https://stardream.pw/link/Ujh5Ch9K1wNhpNZF?surfboard=1 ssr：https://stardream.pw/link/Ujh5Ch9K1wNhpNZF?list=shadowrocket 你这里面clash的链接就可以正常导入了。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
clash支持trojan+v2的，只是订阅链接你需要使用clash的yaml订阅链接

**Comment by Kingtous** [comment]
目前如果导入了一个错误的链接，并生成了yaml文件，请手动在`$HOME/.local/share/cn.kingtous.fclash/clash/`下删除对应的yaml文件再打开。
