### ISSUE TITLE
大佬救命，在flutter SDK 3.7.1上编译失败，小白找了半天没找到依赖文件，我想通过import ... as 来解决

### ISSUE THREAD

**Issue by depfish** [Kingtous/Fclash#30]
> c:\flutter_projects\Fclash>flutter build windows --release

 Building with sound null safety

/C:/flutter_windows_3.7.1-stable/flutter/.pub-cache/hosted/pub.dev/bruno-3.1.0/lib/src/components/tabbar/normal/brn_tab_bar.dart(398,15): error G50A53C35: 'Badge' is imported from both 'package:badges/src/badge.dart' and 'package:flutter/src/material/badge.dart'. [C:\flutter_projects\Fclash\build\windows\flutter\flutter_assemble.vcxproj]
/C:/flutter_windows_3.7.1-stable/flutter/.pub-cache/hosted/pub.dev/bruno-3.1.0/lib/src/components/tabbar/normal/brn_tab_bar.dart(463,17): error G50A53C35: 'Badge' is imported from both 'package:badges/src/badge.dart' and 'package:flutter/src/material/badge.dart'. [C:\flutter_projects\Fclash\build\windows\flutter\flutter_assemble.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(247,5): error MSB8066: Custom build for 'C:\flutter_projects\Fclash\build\windows\CMakeFiles\5e60ace7e92b71f9423cf28ce0855311\flutter_windows.dll.rule;C:\flutter_projects\Fclash\build\windows\CMakeFiles\14b1192a9a1721d7bd5b4fcb54f7be78\flutter_assemble.rule' exited with code 1. [C:\flutter_projects\Fclash\build\windows\flutter\flutter_assemble.vcxproj]
Building Windows application...
Build process failed.

**Comment by depfish** [comment]
@Kingtous 终于搞定了。 大佬，可以考虑支持下最新版本3.7.1的Flutter SDK麽？

目前在最新版本的SDK 上有上面那个包冲突错误。

**Comment by Kingtous** [comment]
> @Kingtous 终于搞定了。 大佬，可以考虑支持下最新版本3.7.1的Flutter SDK麽？
> 
> 目前在最新版本的SDK 上有上面那个包冲突错误。

上游bruno贝壳的ui库的锅。我也在等他发个新版支持。你本地编译进报错的那个bruno源文件，hide掉material的一个badge类，就可以编译。之前我试过。等bruno发个版我升级到3.7..1

**Comment by depfish** [comment]
> l

好的 大佬，加油

**Comment by Kingtous** [comment]
> > l
> 
> 好的 大佬，加油

bruno组件解决了这个问题，有空我升级下

**Comment by Kingtous** [comment]
已更新1.3.9，优化ui，升级flutter base为3.7.1

https://github.com/Kingtous/Fclash/releases/tag/v1.3.9
