### ISSUE TITLE
能否适配Clash.Meta核心

### ISSUE THREAD

**Issue by xubai2001** [Kingtous/Fclash#36]
[Clash.Meta](https://github.com/MetaCubeX/Clash.Meta) 核心是是一个基于开源Clash的二次开发版本，已经实现了TUN, rule-provider等Premium核心的特性， 支持VLESS,、TUIC等协议，规则方面支持GEOSITE、逻辑规则判断， 支持策略组内节点正则筛选 等许多独有的特性([文档](https://clash-meta.wiki/))，而且开发很积极，希望可以考虑一下

**Comment by Kingtous** [comment]
试着切换为了Clash.Meta核心，可以试试

https://github.com/Fclash/Fclash/releases/tag/v1.4.0

**Comment by xubai2001** [comment]
测试了下，如果配置文件内直接写了节点没问题，但是provider的节点和规则无法下载

**Comment by Kingtous** [comment]
更换clash.meta核心后，感觉存在比较严重的性能下降，我这里先把1.4.0标记为prerelease版本
