### ISSUE TITLE
Dark theme wanted!

### ISSUE THREAD

**Issue by yichangshengwu** [Kingtous/Fclash#4]
求添加暗色主题！

**Comment by Kingtous** [comment]
> 求添加暗色主题！

这个我有空就做一下哈。程序里面是打算+黑暗模式的

**Comment by Kingtous** [comment]
1.2.3-1版本发布，支持暗黑模式。可以试用一下

**Comment by yichangshengwu** [comment]
> 1.2.3-1版本发布，支持暗黑模式。可以试用一下

装的 aur 里的，显示装的是 1.2.3-1 呀，
可是运行后，“关于“里面是 1.2.2 了，
什么情况？

**Comment by Kingtous** [comment]
我看了下PKGBUILD，是引用的1.2.3的版本。明天我试试

**Comment by Kingtous** [comment]
我试了下yay安装fclash，没有问题？

**Comment by yichangshengwu** [comment]
> 我试了下yay安装fclash，没有问题？
> 
> ```
> 正在解析依赖关系...
> 正在查找软件包冲突...
> 
> 软件包 (1) fclash-1.2.3-1
> 
> 全部安装大小：  46.72 MiB
> 净更新大小：     0.00 MiB
> 
> :: 进行安装吗？ [Y/n] 
> (1/1) 正在检查密钥环里的密钥                                                                  [######################################################] 100%
> (1/1) 正在检查软件包完整性                                                                    [######################################################] 100%
> (1/1) 正在加载软件包文件                                                                      [######################################################] 100%
> (1/1) 正在检查文件冲突                                                                        [######################################################] 100%
> (1/1) 正在检查可用存储空间                                                                    [######################################################] 100%
> :: 正在运行事务前钩子函数...
> (1/1) Creating Timeshift snapshot before upgrade...
> ==> skipping timeshift-autosnap due skipRsyncAutosnap in /etc/timeshift-autosnap.conf set to TRUE.
> :: 正在处理软件包的变化...
> (1/1) 正在重新安装 fclash                                                                     [######################################################] 100%
> :: 正在运行事务后钩子函数...
> (1/3) Arming ConditionNeedsUpdate...
> (2/3) Refreshing PackageKit...
> (3/3) Updating the desktop file MIME type cache...
> ```
> 
> ![image](https://user-images.githubusercontent.com/39793325/173712146-da39b6a4-b90b-491b-89a6-93e292b810b1.png)

清理了构建，再装一次，这回版本对了，
然而。。。

![截图_2022-06-16_06-59-30](https://user-images.githubusercontent.com/43059917/173956258-baa90280-b4bb-4de5-8c9b-f60daf5cf2e7.png)

这是还有啥需要清理么？

**Comment by Kingtous** [comment]
> 清理了构建，
> 再装一次，
> 这回版本对了，
> 然而。。。
> 
> ![截图_2022-06-16_06-59-30](https://user-images.githubusercontent.com/43059917/173956258-baa90280-b4bb-4de5-8c9b-f60daf5cf2e7.png)
> 
> 这是还有啥需要清理么？
> 难道跟桌面环境有关？咱用的 KDE
> 

设置页面没有办法黑暗模式吗？我这边测试好像可以。我是manjaro kde。我换个系统看看

**Comment by yichangshengwu** [comment]
咱是 arch kde 呢，

哦，补一张截图，当时觉得怪就留了，

![截图_2022-06-16_06-51-07](https://user-images.githubusercontent.com/43059917/173976180-16c33e34-5eac-40ea-9016-b25b4f76ea93.png)

**Comment by Kingtous** [comment]
> 

感谢反馈，我这开个vm试一下

**Comment by TOLIE-OFFICIAL** [comment]
学长，我的也是arch+kde。也是不能暗黑i模式的
![image](https://user-images.githubusercontent.com/90889293/178919130-dddd6699-59e2-4b2f-901f-a5e9f493f27e.png)

还有一个小问题，网速显示有问题，之一都是0，但还是可以访问ytb
![image](https://user-images.githubusercontent.com/90889293/178919595-118c8dfc-dfa3-4aab-ae00-721c7d356807.png)

**Comment by Kingtous** [comment]
> 学长，我的也是arch+kde。也是不能暗黑i模式的 ![image](https://user-images.githubusercontent.com/90889293/178919130-dddd6699-59e2-4b2f-901f-a5e9f493f27e.png)
> 
> 还有一个小问题，网速显示有问题，之一都是0，但还是可以访问ytb ![image](https://user-images.githubusercontent.com/90889293/178919595-118c8dfc-dfa3-4aab-ae00-721c7d356807.png)

有兴趣提个PR吗～
