### ISSUE TITLE
使用kali linux添加的订阅无法切换，也不提示切换失败

### ISSUE THREAD

**Issue by NarClo** [Kingtous/Fclash#6]
在kali上 添加订阅之后 从config切换到自己订阅的配置文件 没反应。点击切换 也不提示错误，还是默认的config配置

**Comment by Kingtous** [comment]
确认添加的是clash订阅链接吗？

**Comment by NarClo** [comment]
是的，订阅连接在win下的clash for windows 是正常使用的，用clash for windows -linux也能正常使用。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月19日(周二) 上午8:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Kingtous/Fclash] 使用kali linux添加的订阅无法切换，也不提示切换失败 (Issue #6)




 
确认添加的是clash订阅链接吗？

**Comment by Kingtous** [comment]
> 是的，订阅连接在win下的clash for windows 是正常使用的，用clash for windows -linux也能正常使用。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年7月19日(周二) 上午8:55 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Kingtous/Fclash] 使用kali linux添加的订阅无法切换，也不提示切换失败 (Issue #6) 确认添加的是clash订阅链接吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

不介意的话，可以提供一下订阅链接吗？可以发我邮箱，我有空看看

**Comment by coolfxin** [comment]
我也遇到了同样的问题，链接是机场提供的，在clash for windows上面可用，在flcash上面就不能用了

**Comment by Kingtous** [comment]
我看了一下，目前fclash只支持clash自己的配置文件（点击链接会下载一个yaml文件的那个），目前fclash需要使用clash的链接才可以。

这个链接是v2ray客户端的，猜测clash for windows是会调用公共api转换成yaml文件的。

所以现在的解决办法是直接导入clash的订阅链接，而不是v2ray的。
下个版本fclash也尝试加入一下自动转换，但是自动转换只能调用公网api，不能保证隐私性。

**Comment by Kingtous** [comment]
如果机场没提供clash的订阅链接，可以将上述链接转换一下。我在网上找了一个可用的，但是不保证隐私性。

`https://hutaosubconverter.com/`

**Comment by coolfxin** [comment]
非常感谢大佬～祝学业顺利



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月24日(星期天) 上午9:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Kingtous/Fclash] 使用kali linux添加的订阅无法切换，也不提示切换失败 (Issue #6)





 
如果机场没提供clash的订阅链接，可以将上述链接转换一下。我在网上找了一个可用的，但是不保证隐私性。
 
https://hutaosubconverter.com/
