### ISSUE TITLE
app显示界面感觉不正常

### ISSUE THREAD

**Issue by covenant-stars** [Kingtous/Fclash#71]
![Screenshot_2023-09-22-20-45-53-123_com fclash fclash](https://github.com/Fclash/Fclash/assets/67546384/f25b3ae8-7a61-430a-b15b-b10dfcb49355)
主界面无图标只有灰色块 状态栏反色异常（miui 安卓13）

**Comment by Kingtous** [comment]
很久没维护android了，可能帮忙看看
