### ISSUE TITLE
什么时候可以升级到.meta内核呢

### ISSUE THREAD

**Issue by AjaxCao** [Kingtous/Fclash#75]
想要用它的Tun模式

**Comment by Kingtous** [comment]
release里面带meta字样的就是

**Comment by AjaxCao** [comment]
但我改了配置文件，增加如下：
tun:
  enable: true
  stack: gvisor
  dns-hijack:
    - 198.18.0.2:53
  auto-route: true
  auto-detect-interface: true

但还是无效，命令行ping google.com还是ping不通
