### ISSUE TITLE
节点太多会挡住功能按钮

### ISSUE THREAD

**Issue by kyanch** [Kingtous/Fclash#8]
这是正常的菜单：
![图片](https://user-images.githubusercontent.com/107523592/186051704-97bfaacc-83cf-4d42-81b2-d80a58a72022.png)
如果节点信息过多，会将整个页面撑的非常长，导致最后的几个按钮(设置系统代理，显示dash，退出)无法被显示到屏幕上:
![图片](https://user-images.githubusercontent.com/107523592/186052271-53004e4c-1cfd-4764-baa1-88d4506e624f.png)
能否将几个功能按钮的位置放在最顶上，或者添加一个滚动条？

**Comment by Kingtous** [comment]
感谢反馈，有兴趣提PR吗？ :)

**Comment by Kingtous** [comment]
![image](https://user-images.githubusercontent.com/39793325/186557487-36dc2711-d4e1-4a65-abab-a606e728e95e.png)
